# theme: jekyll-theme-hacker
title: <em>Eng</em>ineering <em>Prod</em>uctivity at ByteDance
description: We are a data-driven engineering discipline focused on optimizing the engineering process so that ByteDance can deliver amazing experiences to our users, faster.

show_downloads: false
show_repository_url: false
